### ISSUE TITLE
About the MSD loss

### ISSUE THREAD

**Issue by Superman-Valencia** [BlueBlaze6335/FLSGAN-VC#1]
I want to adopt the MSD loss proposed in the paper, but I have met some problems.
Can you tell me the shape of the inputs "ori" and " fake"?

**Comment by BlueBlaze6335** [comment]
We have adopted the loss to calculate the MSD of the original (Target) and the fake (generated) mel spectrograms. The output of the generator (fake) and the target input (ori) are passed as parameters for calculating the loss. Here their dimensions are (batch_size,192,72,1), a 4D tensor. We calculate the MSD over a batch of spectrograms. I hope this helps you.

**Comment by Superman-Valencia** [comment]
> We have adopted the loss to calculate the MSD of the original (Target) and the fake (generated) mel spectrograms. The output of the generator (fake) and the target input (ori) are passed as parameters for calculating the loss. Here their dimensions are (batch_size,192,72,1), a 4D tensor. We calculate the MSD over a batch of spectrograms. I hope this helps you.

Thank you very much for your timely reply. I want to confirm again that 192 is the time dimension, 72 is the channel dimension, and what does the last 1 represent？

**Comment by BlueBlaze6335** [comment]
192 represents the frequency domain (hop_length), 72 represents the time domain. We have added another dimension (using expand_dim) because we have used 2D convolutions (2D conv requires a 4D tensor). So the channel dimension is 1.

**Comment by Superman-Valencia** [comment]
> 192 represents the frequency domain (hop_length), 72 represents the time domain. We have added another dimension (using expand_dim) because we have used 2D convolutions (2D conv requires a 4D tensor). So the channel dimension is 1.

Thank you for answering my questions. It is very helpful to me. Thank you again🤝

**Comment by BlueBlaze6335** [comment]
Dont hesitate to contact me if you have any other doubts. Closing the issue.
